// Generated by Wrangler by running `wrangler types worker-configuration.d.ts`

export interface Env {
  kv: KVNamespace
  r2: R2Bucket
  d1: D1Database
  queue: Queue
  vectorize: VectorizeIndex
  ai: Ai
}
