// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	kv: KVNamespace;
	r2: R2Bucket;
	d1: D1Database;
	queue: Queue;
	vectorize: VectorizeIndex;
	ai: Ai;
}
