app = "v1-zero-cache"
primary_region = "fra"

[build]
image = "registry.hub.docker.com/rocicorp/zero:0.12.2025013001"
include = ["./zero-schema.json"]

[http_service]
internal_port = 4848
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 2
processes = ["app"]

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/"

[[vm]]
size = "shared-cpu-2x"
memory = "2gb"

[mounts]
source = "sqlite_db"
destination = "/data"

[[services]]
protocol = "tcp"
internal_port = 4848
processes = ["app"]

[[services.ports]]
port = 4848

[env]
ZERO_REPLICA_FILE = "/data/sync-replica.db"
ZERO_AUTO_RESET = "true"
ZERO_UPSTREAM_DB = "postgresql://[username]:[password]@db.domain.com:5432/postgres"
ZERO_CVR_DB = "postgresql://[username]:[password]@db.domain.com:5432/postgres_cvr"
ZERO_CHANGE_DB = "postgresql://[username]:[password]@db.domain.com:5432/postgres_change"
ZERO_AUTH_SECRET = "secretkey"
ZERO_SCHEMA_JSON = """{
  "permissions": {
    "medium": {
      "row": {
        "insert": [],
        "update": {
          "preMutation": []
        },
        "delete": []
      }
    },
    ...
}"""
