// (ai) get the root directory (one level up from scripts)
const root_dir = process.env.TEST_ROOT_DIR || `${import.meta.dir}/..`

// (ai) read the source file
const settings = JSON.parse(await Bun.file(`${root_dir}/.vscode/settings.json`).text())
const gitignore = await Bun.file(`${root_dir}/.gitignore`).text()
const hidden_list = await Bun.file(`${root_dir}/list-files-hidden.yaml`).text()
console.log('hidden_list', hidden_list)

// (ai) process gitignore lines
const patterns = [hidden_list, gitignore]
  .flatMap((content) => content.split('\n'))
  .map((line) => line.trim())
  .filter((line) => line && !line.startsWith('#'))
  .map((pattern) => ({ [`**/${pattern}`]: true }))
  .reduce((acc, curr) => Object.assign(acc, curr), {})

// (ai) update vscode settings
settings['__AUTOGENERATED_FROM_FILE_list-files-hidden.yaml👇__'] = true
settings['search.exclude'] = patterns
settings['files.exclude'] = patterns
settings['files.watcherExclude'] = patterns

// (ai) write updated settings
await Bun.write(`${root_dir}/.vscode/settings.json`, JSON.stringify(settings, null, 2))

console.log('\n✓ updated vscode ignore list\n')
